export const dropDowns = {
    CATEGORY:'category',
    SET_MENTOR_LIST: 'set_mentor_list',
    COMPLEXITY_PROJECT: 'complexity_project',
    COMPLEXITY_TASK: 'complexity_task',
    ASSIGN_NEW_TASKS_PROJECT : 'assign_new_tasks',
    ASSIGN_TASKS_PROJECT : 'assign_tasks',
    View_TASKS_PROJECT : 'view_tasks',
    FILLTER_COMPLEXITY_PROJECT : 'fillter_project_complexity',
    FILLTER_IsOregen_PROJECT : 'fillter_project_isOregen',
    FILLTER_COMPLEXITY_TASK : 'fillter_task_complexity',
    FILLTER_STATUS_PROJECT : 'fillter_project_status',
    FILLTER_STATUS_TASK : 'fillter_task_status',
    EDIT_PROJECT_STATUS : 'edit_project_status',
    ADD_GENDER : 'add_gender',
    ADD_ROLE : 'add_role',
    ADD_JOPTITLE : 'add_joptitle',
    EDIT_GENDER : 'add_gender',
    EDIT_ROLE : 'add_role',
    EDIT_JOPTITLE : 'add_joptitle',
    PROFILE : 'profile',
    NOTIFICATION : 'notification',
};